- name: install unattended-upgrades
  apt: name=unattended-upgrades state=present update_cache=yes

- name: run unattended-upgrades
  shell: "unattended-upgrades"

- name: create firewall script
  template:
    src: iptables.sh.j2
    dest: "/etc/iptables.rules"
  notify:
    - "iptables-restore"

- name: create iptables-restore on startup script
  template:
    src: iptables_startup.sh.j2
    dest: "/etc/network/if-pre-up.d/iptables"
    mode: 0755
